name: Deploy On Production
on:
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        RELEASE_BRANCHES: master
  deploy:
    needs: tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rssiweb/portal
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_semver: true
    - name: Trigger Deploy Services
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: rssiweb/services
        event-type: deploy
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

